---
title: Kilómetros construidos de subte en distintas ciudades
author: Martin Olmos
date: '2017-11-02'
slug: kms-de-subte-en-ciudades
categories:
  - R
  - plot.ly
tags: []
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

Breve tutorial sobre cómo hacer un gráfico interactivo de líneas con la [plot.ly para R][1] y [Shiny][2] comparando kilómetros construidos de Subte en Buenos Aires, Madrid, Sao Paulo y Santiago de Chile.
Los datos utilizados son de [citylines.co][3]

```{r}

# Carga las librerías a utilizar
library(shiny)
library(plotly)

# Lee los datos (que ya fueron previamente obtenidos y procesados)
subte_comp <- read.csv("subte_comp.csv")

# Define la interfaz de usuario
ui <- fluidPage(
   # Define el título
   titlePanel("Kilómetros constuidos de subte en distintas ciudades"),
   
   # Define el layout 
   sidebarLayout(
           # Define el panel lateral
           sidebarPanel(
                   # Define el checkbox para seleccionar las ciudades
                   checkboxGroupInput("elegir_ciudades", 
                                      label = "Eligir ciudades",
                                      choices = c("Buenos Aires",
                                                  "Madrid",
                                                  "Sao Paulo", 
                                                  "Santiago"))),
      
      # Define el panel principal
      mainPanel(
         plotlyOutput("subtePlot")
      )
   )
)

# Define la función que se va a implementar en el servidor
server <- function(input, output) {
        
        # 'Escucha' las ciudades seleccionadas en el checkbox para subsetear los datos
        subte_data=reactive({
                return(subte_comp[subte_comp$Ciudad %in% input$elegir_ciudades,])
        })
        
        # Envía el plot en base a las ciudades seleccionadas
        output$subtePlot <- renderPlotly({
                # Define el gráfico de líneas
                plot_ly(data = subte_data(), 
                        x = ~Finalizacion, 
                        y = ~Value,
                        color = ~Ciudad, 
                        type = "scatter",
                        mode = "lines")
   })
}

# Corre la app 
shinyApp(ui = ui, server = server)

```

<iframe src="https://martinolmos.shinyapps.io/subte_comp/" style="border: none; width: 1000px; height: 1000px"></iframe>

[1]:https://plot.ly/r/
[2]:https://shiny.rstudio.com/
[3]:http://www.citylines.co/data