---
title: "Kilómetros constuidos de subte en distintas ciudades"
author: "Martin Olmos"
date: "2017-11-01T15:20:51-03:00"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Gráfico interactivo de líneas simple con Plotly comparando kilómetros constuidos de Subte en distintas ciudades.
Los datos utilizados son de [citylines.com](http://www.citylines.co/data)

```{r, comment=FALSE, message=FALSE, eval=FALSE}
library(shiny)
library(plotly)
library(dplyr)

subte_comp <- read.csv("https://github.com/rbind/r2website/raw/master/content/post/subte_comp.csv")

# Define la interfaz de usuario
ui <- fluidPage(
   # Define el título
   titlePanel("Kilómetros constuidos de subte en distintas ciudades"),
   
   # Define el layout 
   sidebarLayout(
           # Define el panel lateral
           sidebarPanel(
                   # Define el checkbox para seleccionar las ciudades
                   checkboxGroupInput("elegir_ciudades", 
                                      label = "Eligir ciudades",
                                      choices = c("Buenos Aires",
                                                  "Madrid",
                                                  "Sao Paulo", 
                                                  "Santiago"))),
      
      # Define el panel principal
      mainPanel(
         plotlyOutput("subtePlot")
      )
   )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
        
        # 'Escucha' las ciudades seleccionadas en el checkbox para subsetear los datos
        subte_data=reactive({
                return(subte_comp[subte_comp$Ciudad %in% input$elegir_ciudades,])
        })
   output$subtePlot <- renderPlotly({
           # Define el gráfico de líneas
           plot_ly(data = subte_data(), 
                   x = ~Finalizacion, 
                   y = ~Value,
                   color = ~Ciudad, 
                   type = "scatter",
                   mode = "lines")
   })
}

# Corre la app 
shinyApp(ui = ui, server = server)

```

<iframe src="https://martinolmos.shinyapps.io/subte_comp/" style="border: none; width: 1000px; height: 1000px"></iframe>